version: 1.0.{build}

branches:
  only:
  - master
  - appveyor

environment:
  COVERALLS_REPO_TOKEN:
    secure: OlbX7BltbLFKwXViwwUIlcLxJNFOFABIs8Atqi9pDvHSSufhvXjhdZaPHI8RfGVK

configuration: Debug

before_build:
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- nuget install coveralls.net -Version 0.412.0 -OutputDirectory tools

build:
  project: src\RelativeDate.sln
  verbosity: minimal

test_script:
  - ps: .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[RelativeDate*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:RelativeDateTests/bin/Debug/RelativeDateTests.dll" -output:opencoverCoverage.xml
  - ps: .\tools\coveralls.net.0.412\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
